name = "u"
compatibility_date = "2022-05-11"
account_id = "e5d555f9d1fca923675e48bf46bb2a6d"
route = "u.jg.ar/*"

main = "build/index.js"

kv_namespaces = [
  { binding = "URLS", id = "e293fe5dbd964146b5d3f40d1c54f1a2", preview_id = "d3205bfd40c8499b8a924ed56b82ccad" }
]

[site]
bucket = "./public"

[build]
command = "npm run build"
watch_dir = "app"
