name = "ip"
compatibility_date = "2022-05-11"
account_id = "e5d555f9d1fca923675e48bf46bb2a6d"
route = "ip.jg.ar/*"

main = "build/worker/shim.mjs"

[build]
command = "(cargo install -q worker-build || true) && worker-build --release" # required

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
