name = "ip"
main = "build/worker/shim.mjs"
compatibility_date = "2023-04-20"

account_id = "e5d555f9d1fca923675e48bf46bb2a6d"
route = "ip.jg.ar/*"

[build]
command = "(cargo install -q worker-build || true) && worker-build --release" # required
