[package]
name = "cors"
version = "0.1.0"
description = "CORS Anywhere"
authors = ["Jorge Galat <jrgglt@gmail.com>"]
edition = "2018"
repository = "https://github.com/jgalat/jg.ar"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
worker = "0.0.17"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
